travis:
  secure:
    BINSTAR_TOKEN: Jvaev+dR2Tqw53wUQlRqGWBIbYc5cekYBIBgLeLgV1Z9McrptzCTEY1tERHaeQEngdfZoudNbhspj94gMbUvkr4hJRl1Jt/3IsQ37QIHDOT2VYGRopJ9YU/Vg1B9EO/2/7wIb11QstjaAXfp+w7HDfjbFDAVK1rmAjU/78C/rKxAUt+H9ohfsCfl4sdbs7YYmzJ36dLYAeaYoo/DoSaeoRn7seFKfaY7d/LTeaW63OzoQhiwQB+CSptNWVJUgEuQf63BJikqeBEwukofUUryYuhe8LeA+r6APRSdpZyzfrBULVLwWrceUI79pIi4w0Eo4KGxT3IWWY6Ax9mtgHs7tK5sz2UU09rn/KCmMUUESVjDnmTKkHW+IslLfGclE9tC0+tWxqX/+nKzd5K2c40MGq3m6DFTlB3DheXTBMFkQ4KdKUvcyddOIXHrfj65qvrLWjhTOMK3uZtSqf9pQDQEAoXEvD0T1tttNWmf/XJKHxcZ8+38nmV/n7BxhCymzJPWUwkDBHXJ9553OpJ0unW+ibNaZpwiEUjU06vlizqpzoG/l1IBOXvVpbD1uPjXvJF7v8+5swqfQ23KTwdE2PXD90n6AHB0FTZhRGUhHVMmVdvIgaun70KKEbt1Dcz/fl+6A9IfeystDfrQGVLX0aGcZGEL4mLg6OFxPCYN1/Cngd0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
